package ir.jaru.app

/**
 * Catalog of known VPN / tunnel / proxy clients.
 * Used as a second layer on top of VpnService discovery so apps that
 * hide their service or use a helper package still get caught.
 */
object VpnCatalog {
    val packages: Map<String, String> = mapOf(
        // Core clients
        "com.wireguard.android" to "WireGuard",
        "com.wireguard.android.debug" to "WireGuard",
        "de.blinkt.openvpn" to "OpenVPN for Android",
        "net.openvpn.openvpn" to "OpenVPN Connect",
        "net.openvpn.connect.app" to "OpenVPN Connect",
        "org.strongswan.android" to "strongSwan",
        "org.outline.android.client" to "Outline",
        "org.amnezia.vpn" to "AmneziaVPN",
        "org.amnezia.awg" to "AmneziaWG",
        "io.nekohasekai.sagernet" to "SagerNet",
        "io.nekohasekai.sfa" to "sing-box",
        "moe.nb4a" to "NekoBox",
        "moe.nb4a.android" to "NekoBox",
        "com.v2ray.ang" to "v2rayNG",
        "com.v2ray.ang.debug" to "v2rayNG",
        "com.v2raytun.android" to "V2RayTun",
        "com.v2boxn" to "V2Box",
        "com.v2box.v2boxapp" to "V2Box",
        "app.hiddify.com" to "Hiddify",
        "app.hiddify.com.next" to "Hiddify Next",
        "com.hiddify.hiddify" to "Hiddify",
        "com.github.kr328.clash" to "Clash for Android",
        "com.github.kr328.clash.foss" to "Clash Meta FOSS",
        "com.github.kr328.clash.meta" to "Clash Meta",
        "com.github.metacubex.clash.meta" to "Clash Meta",
        "com.github.shadowsocks" to "Shadowsocks",
        "com.github.shadowsocks.tv" to "Shadowsocks TV",
        "com.github.shadowsocks.plugin.obfs" to "SS obfs",
        "com.github.shadowsocks.plugin.v2ray" to "SS v2ray plugin",
        "com.github.shadowsocks.plugin.brook" to "SS brook plugin",
        "io.github.trojan_gfw.igniter" to "Igniter (Trojan)",
        "com.github.chenxiaolong.dualbootpatcher" to "",
        "com.napsternetlabs.napsternetv" to "NapsternetV",
        "com.github.tv48.npv" to "NPV",
        "com.evozi.injector" to "HTTP Injector",
        "com.netmod.lite" to "NetMod",
        "com.everytech.netmod" to "NetMod",
        "com.cloudflare.onedotonedotonedotone" to "1.1.1.1 + WARP",
        "org.torproject.android" to "Orbot",
        "org.torproject.torservices" to "Tor Services",
        "com.psiphon3" to "Psiphon",
        "com.psiphon3.subscription" to "Psiphon Pro",
        "org.getlantern.lantern" to "Lantern",
        "com.ultrasurf.vpn.free" to "UltraSurf",
        "com.tailscale.ipn" to "Tailscale",
        "com.zerotier.one" to "ZeroTier",
        "io.netbird.client" to "NetBird",
        "org.mozilla.firefox.vpn" to "Mozilla VPN",
        "com.mullvad.vpn" to "Mullvad",
        "ch.protonvpn.android" to "Proton VPN",
        "com.protonvpn.android" to "Proton VPN",
        "com.nordvpn.android" to "NordVPN",
        "com.expressvpn.vpn" to "ExpressVPN",
        "com.surfshark.vpnclient.android" to "Surfshark",
        "com.windscribe.vpn" to "Windscribe",
        "com.cyberghost.android.v8" to "CyberGhost",
        "com.cyberghost.android" to "CyberGhost",
        "com.privateinternetaccess.android" to "PIA",
        "com.pia.android" to "PIA",
        "com.tunnelbear.android" to "TunnelBear",
        "com.hotspotshield.android.vpn" to "Hotspot Shield",
        "com.fast.free.unblock.thunder.vpn" to "Thunder VPN",
        "free.vpn.unblock.proxy.turbovpn" to "Turbo VPN",
        "com.supervpn.vpn.free.proxy" to "SuperVPN",
        "com.vpnmaster.android" to "VPN Master",
        "com.atlasvpn.free.android" to "Atlas VPN",
        "com.avast.android.vpn" to "Avast VPN",
        "org.freevpn.vpn" to "Free VPN",
        "com.ivpn.android" to "IVPN",
        "net.ivpn.client" to "IVPN",
        "se.infobyte.wallet" to "",
        "com.cisco.anyconnect.vpn.android.avf" to "Cisco AnyConnect",
        "com.fortinet.forticlient_vpn" to "FortiClient",
        "com.fortinet.forticlient" to "FortiClient",
        "com.paloaltonetworks.globalprotect" to "GlobalProtect",
        "com.pulsesecure.vpn" to "Pulse Secure",
        "net.pulsesecure.vtm" to "Pulse",
        "com.sonicwall.mobileconnect" to "SonicWall",
        "com.checkpoint.VPN" to "Check Point Capsule",
        "com.f5.edge.client" to "F5 Edge",
        "com.arraynetworks.vpn" to "Array VPN",
        "org.openconnect" to "OpenConnect",
        "com.app.openconnect" to "OpenConnect",
        "net.mullvad.mullvadvpn" to "Mullvad",
        "app.intra" to "Intra (DNS)",
        "com.cloudflare.onedotonedotone" to "1.1.1.1",
        "org.xray.app" to "Xray",
        "com.singbox.android" to "sing-box",
        "io.github.saeeddev94.xray" to "Xray",
        "com.v2ray.android" to "V2Ray",
        "com.github.dawndiy.bifrostv" to "BifrostV",
        "com.github.kr328.clash.design" to "Clash",
        "com.github.metacubex.clash" to "Clash Meta",
        "com.happ.proxy" to "Happ",
        "com.happproxy.app" to "Happ",
        "io.github.xray.app" to "Xray",
        "com.leaf.and.aleaf" to "Leaf",
        "com.github.shadowsocks.plugin.kcptun" to "SS kcptun",
        "ru.simpleapps.vpn" to "Simple VPN",
        "com.hide.me.vpn" to "hide.me",
        "com.ivacy" to "Ivacy",
        "com.purevpn" to "PureVPN",
        "com.vpn.securevpn" to "Secure VPN",
        "org.outline.vpn" to "Outline",
        "com.geph.android" to "Geph",
        "io.github.hiddify.next" to "Hiddify",
        "com.tm.vpn" to "TM VPN",
        "com.softether.vpnclient" to "SoftEther",
        "org.mozilla.fenix.vpn" to "Mozilla VPN",
        "com.adguard.vpn" to "AdGuard VPN",
        "com.adguard.android.vpn" to "AdGuard VPN",
        "com.kaspersky.vpn" to "Kaspersky VPN",
        "com.bitdefender.vpn" to "Bitdefender VPN",
        "com.avira.vpn" to "Avira Phantom",
        "com.opera.vpn" to "Opera VPN",
        "com.opera.app.news.vpn" to "Opera",
        "free.vpn.proxy.secure" to "Secure VPN",
        "com.fast.free.vpn.proxy" to "Fast VPN",
        "com.vpn.free.hotspot.secure.vpnify" to "Vpnify",
        "com.protectstar.vpn" to "Protectstar",
        "net.typeblog.socks" to "SocksDroid",
        "com.minproxy" to "MinProxy",
        "com.proxy.shad" to "Shadow",
        "com.github.shadowsocks.plugin.https_simple" to "SS plugin",
        "com.v2ray.ang.foss" to "v2rayNG FOSS",
        "com.github.bannedbook.v2ray.ang" to "v2rayNG bannedbook",
        "com.v2rayn.android" to "v2rayN",
        "com.xrayng.android" to "XrayNG",
        "com.nekobox.android" to "NekoBox",
        "moe.matsuri.lite" to "Matsuri",
        "io.nekohasekai.matsuri" to "Matsuri",
        "com.github.kr328.clash.meta.debug" to "Clash Meta",
        "com.github.metacubex.clash.alpha" to "Clash Meta",
        "com.surfboard.android" to "Surfboard",
        "com.getsurfboard" to "Surfboard",
        "com.github.tianci" to "",
        "com.stash.proxy" to "Stash",
        "com.whinc.stash" to "Stash",
        "com.quantumult" to "Quantumult",
        "ph.telegra.vpn" to "Telegram VPN extra",
        "org.telegram.messenger.webvpn" to "",
        "com.ss.android.ugc.aweme" to "",
        "com.android.vpndialogs" to "سیستم — دیالوگ VPN"
    ).filterValues { it.isNotEmpty() }

    val skipAlways = setOf(
        "ir.jaru.app",
        "com.android.vpndialogs",
        "com.android.networkstack",
        "com.android.networkstack.tethering",
        "com.google.android.networkstack",
        "com.android.systemui",
        "com.android.settings"
    )

    val nameKeys = listOf(
        "vpn", "v2ray", "v2box", "v2rayng", "v2rayn", "xray", "clash", "meta cubex",
        "wireguard", "wire guard", "openvpn", "open vpn", "shadowsocks", "shadow rocket",
        "shadowrocket", "hysteria", "trojan", "hiddify", "sagernet", "nekobox", "neko box",
        "singbox", "sing-box", "sing box", "warp", "psiphon", "orbot", "outline",
        "tun2socks", "napsternet", "surfboard", "stash proxy", "quantumult",
        "openconnect", "anyconnect", "forticlient", "globalprotect", "tailscale",
        "zerotier", "mullvad", "protonvpn", "proton vpn", "nordvpn", "nord vpn",
        "expressvpn", "surfshark", "windscribe", "tunnelbear", "hotspot shield",
        "cyberghost", "amnezia", "lantern", "ultrasurf", "http injector", "netmod",
        "softether", "strongswan", "ipsec", "ikev2", "l2tp", "pptp vpn",
        "socks droid", "socksdroid", "tun2", "xrayng", "matsuri", "geph",
        "happ proxy", "v2raytun", "adguard vpn", "mozilla vpn", "cloudflare warp",
        "1.1.1.1", "hide.me", "purevpn", "ivacy", "pia vpn"
    )

    fun looksLikeVpn(pkg: String, label: String): String? {
        val blob = (pkg + " " + label).lowercase()
        return nameKeys.firstOrNull { blob.contains(it) }
    }
}
